baseURL = https://ashy-tree-0c3f84f00.3.azurestaticapps.net"
languageCode = "en"
title = "Leizl Reyes - Hugo App"
theme = "hugo-initio"

tags = ["blog","responsive","personal","google analytics","portfolio","disqus","bootstrap","font awesome","projects","creative","landing page","product","white","share this"]
features = ["blog","responsive","personal","google analytics","portfolio","disqus","bootstrap","font awesome","projects","creative","landing page","product","white","share this"]
min_version = "0.68.3"

[params]
    name = "WHOAMI? Hi! IAM <Leizl>"
    description = "Cloud Engineer and Entrepreneur"
    email = "jleizlreyes@gmail.com"
    phone = "09173264942"
    address = "Catanauan, Quezon Province, Philippines"
    year = 2023
    avatar = "images/brown.jpg"
    avatarclass = "circle"
    background = ""
    banner = "images/lv - Copy.jpg"
    favicon = "images/butterfly.jpg"
    DateForm = "August 10, 2023"
    # author = "Sergey Pozhilov (GetTemplate.com)"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownloads = true
    showClients = true

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = true
    showFooterFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/jleizlreyes/"
    icon = "fab fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/Jleizl"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/jleizlreyes/"
    icon = "fab fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+nickname"
    icon = "fab fa-google-plus-square"
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/jayleizlreyes/"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nickname.tumblr.com"
    icon = "fab fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/jleizl"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "jleizlreyes@gmail.com"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"
